# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVmaze' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVmaze

pod 'Alamofire'


  target 'TVmazeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVmazeUITests' do
    # Pods for testing
  end

end
